# Generated by Django 3.2.5 on 2023-05-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='Name',
            new_name='name',
        ),
    ]
