# Generated by Django 3.2.5 on 2023-05-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_artist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='artists',
            new_name='artist',
        ),
    ]
